### ISSUE TITLE
Migrating from tailwindcss

### ISSUE THREAD

**Issue by u12206050** [windicss/gridsome-plugin-windicss#1] opened 2021-03-27 14:23 UTC
So i tried to migrate to windi from tailwindcss but some of the tailwind styles stopped working.

I did the following:

1. Removed tailwindcss and installed windicss
2. Installed the plugin `gridsome-plugin-windicss`
3. Renamed tailwind.config.js > windi.config.js
4. Removed @tailwind imports in my `styles.scss`

Any ideas?

**Comment by harlan-zw** [comment] 2021-03-29 05:33
Hey @u12206050 

Did you follow the migration docs: https://windicss.org/guide/migration.html#tailwind-config-js?

If you did and still have version try update the package.

If it's still not working can you either setup a reproduction repo or let me know exactly what isn't working. Also there's an example of how wind is used if that helps: https://github.com/windicss/gridsome-plugin-windicss/tree/master/test/fixture

**Comment by harlan-zw** [comment] 2021-05-03 10:42
Closing because there was no reply

**Closed as completed by harlan-zw** 2021-05-03 10:42 UTC
